import { useMemo, useState } from 'react';
import ClinicianLogin from '../components/ClinicianLogin';
import PatientQueue from '../components/PatientQueue';
import EHRLayout from '../components/EHRLayout';
import ScriptAssistDock from '../components/ScriptAssistDock';
import pharmaData from '../data/pharmaData.json';
import { dosingOptionsFor } from '../data/dosingOptions';

const patients = [
  { name: 'Marcus Vance', age: 42, dob: '04/12/1984', id: '#98421-E', diagnosis: 'Moderate-to-Severe Plaque Psoriasis (L40.0)', secondaryProblem: 'Hypertension', insurance: 'BlueCross BlueShield of Georgia', insuranceShort: 'BCBS GA', priority: 'High', appointment: '9:00 AM', visit: 'Follow-up · Dermatology', defaultDrug: 'stelazio' },
  { name: 'Aisha Patel', age: 35, dob: '09/22/1991', id: '#77108-E', diagnosis: 'Moderate-to-Severe Atopic Dermatitis (L20.9)', secondaryProblem: 'Seasonal allergic rhinitis', insurance: 'Aetna Open Choice PPO', insuranceShort: 'Aetna', priority: 'High', appointment: '9:20 AM', visit: 'New therapy start', defaultDrug: 'dupixent' },
  { name: 'Liam Chen', age: 49, dob: '01/16/1977', id: '#55173-E', diagnosis: 'Psoriatic Arthritis (L40.50)', secondaryProblem: 'Type 2 diabetes mellitus', insurance: 'UnitedHealthcare Choice Plus', insuranceShort: 'UHC', priority: 'Medium', appointment: '9:40 AM', visit: 'Medication follow-up', defaultDrug: 'humira' },
  { name: 'Elena Rodriguez', age: 38, dob: '11/03/1987', id: '#67014-E', diagnosis: 'Plaque Psoriasis (L40.0)', secondaryProblem: 'Migraine', insurance: 'Cigna Open Access Plus', insuranceShort: 'Cigna', priority: 'Medium', appointment: '10:15 AM', visit: 'Prior authorization review', defaultDrug: 'cosentyx' },
  { name: 'Noah Williams', age: 56, dob: '06/18/1970', id: '#29136-E', diagnosis: 'Rheumatoid Arthritis (M06.9)', secondaryProblem: 'Hyperlipidemia', insurance: 'Medicare Advantage', insuranceShort: 'Medicare', priority: 'Medium', appointment: '10:40 AM', visit: 'Treatment escalation', defaultDrug: 'rinvoq' },
  { name: 'Sophie Kim', age: 28, dob: '02/09/1998', id: '#83725-E', diagnosis: 'Crohn’s Disease (K50.90)', secondaryProblem: 'Iron deficiency anemia', insurance: 'BlueCross BlueShield of Georgia', insuranceShort: 'BCBS GA', priority: 'Low', appointment: '11:00 AM', visit: 'Maintenance review', defaultDrug: 'entyvio' },
  { name: 'Daniel Brooks', age: 45, dob: '08/21/1980', id: '#31460-E', diagnosis: 'Atopic Dermatitis (L20.9)', secondaryProblem: 'Asthma', insurance: 'Aetna Open Choice PPO', insuranceShort: 'Aetna', priority: 'Low', appointment: '11:20 AM', visit: 'Established patient', defaultDrug: 'dupixent' },
  { name: 'Priya Shah', age: 51, dob: '12/02/1974', id: '#49218-E', diagnosis: 'Plaque Psoriasis (L40.0)', secondaryProblem: 'Obesity', insurance: 'UnitedHealthcare Choice Plus', insuranceShort: 'UHC', priority: 'Low', appointment: '11:40 AM', visit: 'Routine follow-up', defaultDrug: 'skyrizi' }
  ,{ name: 'Jordan Foster', age: 33, dob: '06/27/1993', id: '#11936-E', diagnosis: 'Plaque Psoriasis (L40.0)', secondaryProblem: 'Generalized anxiety disorder', insurance: 'Cigna Open Access Plus', insuranceShort: 'Cigna', priority: 'High', appointment: '12:00 PM', visit: 'New advanced-therapy consult', defaultDrug: 'tremfya' }
  ,{ name: 'Mei Lin', age: 61, dob: '03/14/1965', id: '#86021-E', diagnosis: 'Rheumatoid Arthritis (M06.9)', secondaryProblem: 'Osteopenia', insurance: 'Medicare Advantage', insuranceShort: 'Medicare', priority: 'Medium', appointment: '1:00 PM', visit: 'DMARD review', defaultDrug: 'methotrexate' }
  ,{ name: 'Omar Haddad', age: 47, dob: '07/09/1979', id: '#40612-E', diagnosis: 'Psoriatic Arthritis (L40.50)', secondaryProblem: 'Gastroesophageal reflux disease', insurance: 'BlueCross BlueShield of Georgia', insuranceShort: 'BCBS GA', priority: 'Medium', appointment: '1:20 PM', visit: 'Joint symptom follow-up', defaultDrug: 'taltz' }
  ,{ name: 'Grace Miller', age: 29, dob: '01/30/1997', id: '#74618-E', diagnosis: 'Atopic Dermatitis (L20.9)', secondaryProblem: 'Allergic asthma', insurance: 'Aetna Open Choice PPO', insuranceShort: 'Aetna', priority: 'Low', appointment: '1:40 PM', visit: 'Topical treatment review', defaultDrug: 'tacrolimus' }
  ,{ name: 'Victor Alvarez', age: 54, dob: '10/18/1972', id: '#23549-E', diagnosis: 'Plaque Psoriasis (L40.0)', secondaryProblem: 'Hyperlipidemia', insurance: 'UnitedHealthcare Choice Plus', insuranceShort: 'UHC', priority: 'Low', appointment: '2:00 PM', visit: 'Oral treatment discussion', defaultDrug: 'otezla' }
];

const emptyOrder = { dosingPlan: '', dosage: '', frequency: '', quantity: '', refills: '3', daw: 'DAW-1', notes: 'Patient tried and failed topical betamethasone and calcipotriene for > 6 months. High PASI score. Failed phototherapy due to clinic distance.' };
const orderFor = (drug) => { const plan = dosingOptionsFor(drug)[0]; return { ...emptyOrder, dosingPlan: plan.id, dosage: plan.dosage, frequency: plan.frequency, quantity: plan.quantity }; };

export default function Home() {
  const drugs = useMemo(() => Object.values(pharmaData.drugs), []); const [screen, setScreen] = useState('login'); const [queueView, setQueueView] = useState('grid'); const [patient, setPatient] = useState(null); const [selectedDrug, setSelectedDrug] = useState(null); const [order, setOrder] = useState(emptyOrder);
  const [copayAttached, setCopayAttached] = useState(false); const [tbLabOrdered, setTbLabOrdered] = useState(false); const [sampleOrdered, setSampleOrdered] = useState(false); const [bridgeDispatched, setBridgeDispatched] = useState(false); const [selectedLanguage, setSelectedLanguage] = useState('English'); const [transmitted, setTransmitted] = useState(false); const [toast, setToast] = useState(null);
  const notify = (title, message) => { setToast({ title, message }); window.setTimeout(() => setToast(null), 3500); };
  const resetWorkflow = () => { setCopayAttached(false); setTbLabOrdered(false); setSampleOrdered(false); setBridgeDispatched(false); setSelectedLanguage('English'); setTransmitted(false); };
  const openPatient = (nextPatient) => { const drug = pharmaData.drugs[nextPatient.defaultDrug]; setPatient(nextPatient); setSelectedDrug(drug); setOrder(orderFor(drug)); resetWorkflow(); setScreen('prescribe'); };
  const selectDrug = (drug) => { setSelectedDrug(drug); setOrder(orderFor(drug)); resetWorkflow(); };
  const selectAlternative = (drug) => { selectDrug(drug); notify('Draft updated for clinician review', `${drug.brandName} has replaced the previous selection in this unsigned draft.`); };
  const updateOrder = (nextOrder) => { setOrder(nextOrder); };
  const changeDosePlan = (plan) => { setOrder((current) => ({ ...current, dosingPlan: plan.id, dosage: plan.dosage, frequency: plan.frequency, quantity: plan.quantity })); resetWorkflow(); notify('Dosing plan updated', 'Dose, frequency, quantity, and ScriptAssist details now reflect the selected draft plan.'); };
  const returnToQueue = () => { setScreen('queue'); setPatient(null); setSelectedDrug(null); setOrder(emptyOrder); };
  const save = () => selectedDrug ? notify('Draft saved', `The ${selectedDrug.brandName} order is saved to ${patient.name}'s chart.`) : notify('Select a medication', 'Choose a therapy before saving an order.');
  const cancel = () => { setSelectedDrug(null); setOrder(emptyOrder); resetWorkflow(); notify('Order cancelled', 'The draft and ScriptAssist workflow have been cleared.'); };
  const transmit = () => selectedDrug ? (setTransmitted(true), notify('Order transmitted', 'The specialty pharmacy has received the signed e-script.')) : notify('Select a medication', 'Choose a therapy before transmitting an order.');
  if (screen === 'login') return <ClinicianLogin onSignIn={() => setScreen('queue')} />;
  if (screen === 'queue') return <PatientQueue patients={patients} view={queueView} onViewChange={setQueueView} onOpenPatient={openPatient} onSignOut={() => setScreen('login')} />;
  return <main className="app dashboard-app"><header><div className="ehr-logo"><i>+</i> CarePulse <span>v4.2 &nbsp;|&nbsp; Dr. Zaman, MD &nbsp;|&nbsp; Midtown Health</span></div><div className="brand"><i /><div><b>ScriptAssist</b><small>powered by impiricus</small></div></div></header><div className="layout dashboard-layout"><EHRLayout key={patient.id} patient={patient} drugs={drugs} selectedDrug={selectedDrug} order={order} onOrderChange={updateOrder} onDosePlanChange={changeDosePlan} onSelectDrug={selectDrug} copayAttached={copayAttached} onSwitchPatient={returnToQueue} onSave={save} onCancel={cancel} onTransmit={transmit} transmitted={transmitted} /><ScriptAssistDock drug={selectedDrug} drugs={drugs} patient={patient} order={order} copayAttached={copayAttached} tbLabOrdered={tbLabOrdered} sampleOrdered={sampleOrdered} bridgeDispatched={bridgeDispatched} selectedLanguage={selectedLanguage} onAttachCopay={() => { setCopayAttached(true); notify('Secondary billing attached', `${selectedDrug.copay.patientCost} co-pay data has been added to the e-script.`); }} onOrderLab={() => { setTbLabOrdered(true); notify('TB lab panel attached', 'QuantiFERON-TB Gold has been added to the order.'); }} onOrderSample={() => { setSampleOrdered(true); notify('Starter kits confirmed', 'McKesson Logistics will ship overnight to Clinic Suite 400.'); }} onDispatchBridge={() => { setBridgeDispatched(!bridgeDispatched); notify(bridgeDispatched ? 'Bridge supply cancelled' : 'Bridge supply dispatched', bridgeDispatched ? 'No direct-to-patient shipment will be sent.' : `A 14-day dose will ship to ${patient.name}.`); }} onLanguageChange={setSelectedLanguage} onPrintInstructions={() => notify('Patient instructions ready', `${selectedLanguage} after-visit summary prepared.`)} onSelectAlternative={selectAlternative} /></div>{toast && <div className="toast"><b>{toast.title}</b><span>{toast.message}</span></div>}</main>;
}
