import { useEffect, useState } from 'react';

const copyFor = (drug, language, order) => ({
  title: language === 'English' ? `Starting ${drug.brandName}` : language === 'Español' ? `Cómo comenzar ${drug.brandName}` : `Bắt đầu dùng ${drug.brandName}`,
  instructions: language === 'English' ? `1. Review your medication and supplies.\n2. Follow your care team’s schedule: ${order.frequency}.\n3. Your current draft dose is ${order.dosage}. Store the medication as directed and call your care team with questions.` : language === 'Español' ? `1. Revise su medicamento y suministros.\n2. Siga el horario de su equipo de atención: ${order.frequency}.\n3. La dosis actual en borrador es ${order.dosage}. Guarde el medicamento según las instrucciones y llame a su equipo si tiene preguntas.` : `1. Kiểm tra thuốc và vật dụng của bạn.\n2. Làm theo lịch của nhóm chăm sóc: ${order.frequency}.\n3. Liều hiện tại trong bản nháp là ${order.dosage}. Bảo quản thuốc theo hướng dẫn và gọi nhóm chăm sóc nếu có câu hỏi.`,
  nurseLine: '24/7 Nurse Concierge: 1-800-555-0184'
});

export default function HandoutEditor({ drug, patient, language, order, onPrint }) {
  const [handout, setHandout] = useState(() => copyFor(drug, language, order)); const [imageUrl, setImageUrl] = useState(null); const [imageState, setImageState] = useState('idle'); const [fda, setFda] = useState(null); const [fdaState, setFdaState] = useState('idle');
  useEffect(() => { setHandout(copyFor(drug, language, order)); setImageUrl(null); setImageState('idle'); setFda(null); setFdaState('idle'); }, [drug.id, language, order.dosage, order.frequency]);
  const update = (field) => (event) => setHandout({ ...handout, [field]: event.target.value });
  const generateVisual = async () => { setImageState('loading'); try { const therapyType = drug.defaultDose.toLowerCase().includes('oral') ? 'oral medication' : 'injection pen'; const response = await fetch('/api/generate-instruction-image', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ therapyType }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setImageUrl(payload.imageUrl); setImageState('ready'); } catch (error) { setImageState(error.message || 'Image generation failed.'); } };
  const loadFda = async () => { setFdaState('loading'); try { const response = await fetch(`/api/drug-label?brand=${encodeURIComponent(drug.brandName)}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setFda(payload); setFdaState('ready'); } catch (error) { setFdaState(error.message || 'FDA lookup failed.'); } };
  return <><div className="handout-meta"><span>{patient.name}</span><span>{drug.brandName}</span><span>{language}</span></div><div className="handout-editor"><label>Handout title<input value={handout.title} onChange={update('title')} /></label><label>Instructions<textarea value={handout.instructions} onChange={update('instructions')} /></label><label>Nurse support line<input value={handout.nurseLine} onChange={update('nurseLine')} /></label></div><div className="handout-tools"><button className="wide outline" onClick={generateVisual} disabled={imageState === 'loading'}>{imageState === 'loading' ? 'Generating visual…' : 'Generate instruction visual'}</button><button className="text-action" onClick={loadFda} disabled={fdaState === 'loading'}>{fdaState === 'loading' ? 'Looking up FDA label…' : 'Add FDA label reference'}</button></div>{imageState !== 'idle' && imageState !== 'loading' && !imageUrl && <p className="handout-error">{imageState}</p>}{imageUrl && <img className="instruction-visual" src={imageUrl} alt="Generated medication instruction illustration" />}{fda && <div className="fda-reference"><div className="eyebrow">FDA label reference</div>{fda.indication && <p><b>Indication:</b> {fda.indication}</p>}{fda.dosage && <p><b>Label dosage:</b> {fda.dosage}</p>}<small>Source: {fda.source}. Verify against the full FDA label before clinical use.</small></div>}{fdaState !== 'idle' && fdaState !== 'loading' && !fda && <p className="handout-error">{fdaState}</p>}<div className="handout-preview"><div className="eyebrow">Patient copy</div><h3>{handout.title}</h3><p>{handout.instructions}</p><div className="handout-footer"><b>{drug.copay.patientCost} co-pay card activated</b><span>{handout.nurseLine}</span></div></div><button className="wide" onClick={() => onPrint(handout)}>Print patient instructions</button></>;
}
