import { useState } from 'react';
import HandoutEditor from './HandoutEditor';
import AlternativePathways from './AlternativePathways';

function Modal({ title, children, onClose }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><button className="close" onClick={onClose} aria-label="Close">×</button><div className="eyebrow">ScriptAssist document center</div><h2>{title}</h2>{children}</div></div>; }

export default function ScriptAssistDock({ drug, drugs, patient, order, copayAttached, tbLabOrdered, sampleOrdered, bridgeDispatched, selectedLanguage, onAttachCopay, onOrderLab, onOrderSample, onDispatchBridge, onLanguageChange, onPrintInstructions, onSelectAlternative }) {
  const [tab, setTab] = useState('coverage'); const [modal, setModal] = useState(null);
  if (!drug) return <aside className="dock empty"><div><div className="pulse">+</div><b>ScriptAssist is ready</b><p>Select a medication to review coverage and support options.</p></div></aside>;
  const missing = drug.criteria.find((item) => !item.met);
  return <aside className="dock dashboard-dock"><div className="dock-hero"><div className="eyebrow">Impiricus patient support</div><h2>ScriptAssist</h2><p>{drug.brandName} · {order.dosage} · {order.frequency}</p></div><nav className="tabs" aria-label="ScriptAssist sections"><button className={tab === 'coverage' ? 'active' : ''} onClick={() => setTab('coverage')}>Coverage &amp; Copay</button><button className={tab === 'pa' ? 'active' : ''} onClick={() => setTab('pa')}>Prior Auth</button><button className={tab === 'alternatives' ? 'active' : ''} onClick={() => setTab('alternatives')}>Alternatives</button><button className={tab === 'fulfillment' ? 'active' : ''} onClick={() => setTab('fulfillment')}>Fulfillment</button></nav>
    <div className="tab-content">
      {tab === 'coverage' && <><section className="card radar"><div className="card-label">Real-time formulary tier radar</div><div className="tier"><b>Tier 4</b><span>Specialty · Prior Authorization Required</span></div><div className="price-row"><span>Estimated retail copay</span><b>{drug.listPrice}</b></div><div className="alternative"><b>Formulary alternative — not selected</b><span>{drug.alternative}</span></div></section><section className="card voucher"><div className="card-label">Manufacturer co-pay savings voucher</div><div className="cost"><span>Patient pays</span><b>{drug.copay.patientCost}</b><small>Saving {drug.copay.savings}</small></div><div className="claims">RxBIN {drug.copay.bin} · PCN {drug.copay.pcn}<br />Group {drug.copay.group} · ID {drug.copay.id}</div><button className={copayAttached ? 'wide success' : 'wide'} onClick={onAttachCopay}>{copayAttached ? '✓ Secondary billing attached' : 'Attach Secondary Billing to E-Script'}</button><button className="text-action" onClick={() => setModal('voucher')}>Print instant physical co-pay card</button></section></>}
      {tab === 'pa' && <><section className="card"><div className="card-label">Automated criteria checklist</div><div className="criteria">{drug.criteria.map((item) => <div key={item.id} className={!item.met && !tbLabOrdered ? 'criterion missing' : 'criterion'}><b>{!item.met && !tbLabOrdered ? '!' : '✓'}</b><span>{!item.met && tbLabOrdered ? 'QuantiFERON-TB Gold panel ordered' : item.label}<small>{!item.met && tbLabOrdered ? 'Lab order attached to e-script' : item.source}</small></span></div>)}</div>{missing && !tbLabOrdered && <button className="wide" onClick={onOrderLab}>1-Click Order TB Lab Panel</button>}</section><section className="card appeal"><div className="card-label">Peer-to-peer appeal packet</div><p>Ready-to-read talking points built from the clinical note.</p><button className="wide outline" onClick={() => setModal('appeal')}>Generate Denial Defense Brief</button></section></>}
      {tab === 'alternatives' && <AlternativePathways patient={patient} drug={drug} drugs={drugs} onSelectAlternative={onSelectAlternative} />}
      {tab === 'fulfillment' && <><section className="card"><div className="card-label">Physical clinic sample restock</div><div className="stockline"><span>In-clinic stock</span><b>{drug.samples.remaining} units</b></div><small>{drug.samples.package}</small><button className={sampleOrdered ? 'wide success' : 'wide'} onClick={onOrderSample}>{sampleOrdered ? '✓ Starter kits confirmed' : 'Request 2 Starter Kits to Clinic'}</button>{sampleOrdered && <p className="success-copy">Shipping via McKesson Logistics overnight to Clinic Suite 400.</p>}</section><section className="card bridge"><div><div className="card-label">14-day free digital bridge supply</div><p>Start therapy while insurance processes.</p></div><button className={bridgeDispatched ? 'toggle on' : 'toggle'} onClick={onDispatchBridge} aria-pressed={bridgeDispatched}><i /></button>{bridgeDispatched && <p className="success-copy">Bridge dose dispatched directly to {patient.name}.</p>}</section><section className="card instructions"><div className="card-label">Patient onboarding handout</div><select value={selectedLanguage} onChange={(event) => onLanguageChange(event.target.value)}><option>English</option><option>Español</option><option>Tiếng Việt</option></select><div className="sheet-preview"><b>{selectedLanguage === 'English' ? 'Your first injection' : selectedLanguage === 'Español' ? 'Su primera inyección' : 'Mũi tiêm đầu tiên của bạn'}</b><span>1. Prepare pen &nbsp; 2. Inject &nbsp; 3. Call nurse concierge</span><small>24/7 manufacturer nurse support · Co-pay card activated</small></div><button className="wide outline" onClick={() => setModal('instructions')}>Preview and edit instructions</button></section></>}
    </div>
    {modal === 'voucher' && <Modal title="Instant co-pay card" onClose={() => setModal(null)}><div className="voucher-card"><b>{drug.brandName} savings card</b><strong>Patient pays {drug.copay.patientCost}</strong><div className="barcode">||| || |||| | ||| || ||||</div><small>{drug.copay.id} · RxBIN {drug.copay.bin} · Group {drug.copay.group}</small></div><button className="wide" onClick={() => setModal(null)}>Print voucher</button></Modal>}
    {modal === 'appeal' && <Modal title="Denial defense brief" onClose={() => setModal(null)}><ul className="brief"><li><b>Clinical summary:</b> {drug.appeal.summary}</li><li><b>Evidence:</b> {drug.appeal.trial}</li><li><b>Medical necessity:</b> {drug.appeal.rationale}</li><li><b>Draft dose &amp; schedule:</b> {order.dosage}, {order.frequency}. Verify against the current FDA label before clinical use.</li></ul><button className="wide" onClick={() => setModal(null)}>Print appeal brief</button></Modal>}
    {modal === 'instructions' && <Modal title="Preview patient instructions" onClose={() => setModal(null)}><HandoutEditor drug={drug} patient={patient} language={selectedLanguage} order={order} onPrint={() => { onPrintInstructions(); setModal(null); }} /></Modal>}
  </aside>;
}
